name: Auto Tag

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important to get all tags
          github_token: ${{ secrets.GITHUB_TOKEN }} # Only Idrice can set or see this token under setting of repository!!
          force_orphan: true # allows you to make your publish branch with only the latest commit

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get latest tag
        id: tagger
        run: |
            latest=$(git tag --sort=v:refname | grep '^v' | tail -n 1)
            if [ -z "$latest" ]; then
              latest="v0.0.0.0"
            fi
            
            version=${latest#v}
            IFS='.' read -ra parts <<< "$version"
            last_index=$((${#parts[@]} - 1))
            parts[$last_index]=$((10#${parts[$last_index]} + 1))

            new_version="v${parts[0]}"
            for i in "${parts[@]:1}"; do
              new_version+=" .${i}"
              done

              echo "New tag: $new_version"
              echo "new_tag=$new_version" >> "$GITHUB_ENV"

      - name: Create Git tag
        run: |
          git tag ${{ steps.tagger.outputs.new_tag }}
          git push origin ${{ steps.tagger.outputs.new_tag }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
