name: Update Tag Version

on:
  workflow_dispatch:   # allows manual trigger

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch all history to access tags

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Determine new tag version
        id: vars
        run: |
          # Get latest tag
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $LATEST_TAG"

          # Increment patch version (vX.Y.Z)
          IFS='.' read -r MAJOR MINOR PATCH <<< "${LATEST_TAG#v}"
          PATCH=$((PATCH + 1))
          NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          echo "New tag: $NEW_TAG"

          # Save as output
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Create new tag
        run: |
          git tag -a ${{ steps.vars.outputs.new_tag }} -m "Auto tag from CI"
          git push origin ${{ steps.vars.outputs.new_tag }}
